### ISSUE TITLE
movies.html

### ISSUE THREAD

**Issue by kentaiwami** [kentaiwami/FiNote#1]
### TODO
- [x] 検索&表示切り替え
    - [x] 検索バーをリストの上部に設置する。
    - [x] 検索ボタンが押されたら、
      - [x] 正規表現を使って映画タイトルの検索を行う。
      - [x] オノマトペテーブルから検索して、映画テーブルの検索と結合する。
      - [x] リストヘッダーの文字を変える。
      - [x] 検索結果をリスト表示する。
      - [x] 検索結果が0の場合は、該当映画なしのメッセージを表示する。
      - [x] 検索結果が0以外の場合は、該当映画をリスト表示する。
    - [x] 入力文字数が1文字以上ならリセットボタンを表示する。
    - [x] 入力文字数が0文字ならリセットボタンを非表示にする。
    - [x] リセットボタンがタップされたら、inputのvalueを空にして、ヘッダーを「全て」にして結果を表示する。
- [x] ＋ボタンを押したら登録画面へpushで遷移する．
- [x] 登録する映画のテーブルのデータベースを構築する．
- [x] DBから取得したmoviesをもとに、DVD情報と映画タイトルを表示する。
- [x] 検索画面から戻る際はmovies画面の再描画を行う。
- [x] dvd,favボタンを押したら該当する映画レコードの更新を行う。
- [x] DBにお気に入りのカラムを追加する。
- [x] DBから取得したお気に入りの情報をもとにハートに色を付ける。
- [x] moviesのオノマトペIDをもとにオノマトペ名を取得して表示する。
- [x] 追加した順から表示する。
- [x] 追加日を表示する
- [x] DVD、Favが登録されていることをリスト上に表示する。
- [x] タブのアイコンの色を変更する。
- [x] 詳細ボタンを押したら映画の詳細画面へ遷移させる。
