### ISSUE TITLE
movieadd.html

### ISSUE THREAD

**Issue by kentaiwami** [kentaiwami/FiNote#3]
### TODO
- [x] 吹き出しボタンを押したらiOSのミュージックみたいな画像タップで歌詞表示する動作をして「タイトル，概要，公開日」を表示(詳細表示)する．
- [x] 画像タップでも同様に詳細表示する．
- [x] 詳細表示している時に画像タップor吹き出しボタンをタップしたら詳細表示を消す．
- [x] レーティングの表示を映画オブジェクトのレーティングをもとに表示する．
- [x] レーティング下部のアクション一覧は，「追加，シェア，オノマトペ記入」にする．
- [x] 「オノマトペ記入」をタップしたらオノマトペ記入画面へ遷移する．
- [x] 登録されている気分リストの件数とDVD所持の情報をもとにYES or NOを表示する。
- [x] データが登録されていない状態で「追加」ボタンをタップしたらアラートを表示する。
- [x] 「追加」ボタンをタップしたら
  - [x] 画面に表示されている全てのボタンを無効にする。 
  - [x] NCMBデータベースへ記録
  - [x] NCMBのMovieクラスのUserNameには既に登録されていたら自分自身のユーザ名を追加せずに更新する。
  - [x] Localデータベースへ記録
  - [x] ジャンルとオノマトペをLocalへ記録する関数は、ローカルからリストを取得してリスト内に含まれていたら記録しないようにする。記録処理はPromise.Allを使用する。
  - [x] movieを記録する。
  - [x] dvd所持の情報を記録する。
  - [x] スピナ表示
  - [x] 登録完了のアラートを表示
  - [x] 映画検索画面へ戻る．
  - [x] エラーが発生したら、メッセージをアラートで表示する。
- [x] アラートの"OK"をタップしたら映画検索画面へ遷移する．
- [x] 映画の概要が長い場合は見切れない文字列の長さまでカットして末尾に...を表示する。
- [x] 「シェア」を押したらSNS立ち上げ
- [x] お気に入りは0をデフォルトとして記録する。
- [x] 気分リストの登録件数の表示を数字のみにする。
- [x] 気分リストに1件でも登録があれば、追加ボタンに色をつける。
- [x] チェックボックスの色を変更する。

### Bug
- [x] フォームが所定位置に移動後＆入力文字確定後にリセットボタンを押した際に余計なアニメーションをしてしまう．
- [x] テキスト入力が未確定の状態でリセットボタンを押すとフォーカスが外れてアニメーションが実行されてしまう．
- [x] キャンセルボタンの領域が広い!?
- [x] リセットボタンの領域が小さすぎる!?
- [x] 文字を入力した後にフォーカスを外すとリセットボタンの場所がずれている．
- [x] noimageの画像が見切れてしまう．
- [x] 映画追加が完了した後に表示されるアラートのOKボタンが押せない。映画の詳細情報が反応してしまう。
- [x] SNS投稿(TwitterとLINE)でキャンセルをしても投稿完了のアラートが表示されてしまう。
- [x] DVDのアイコンが見切れてしまっている。
- [x] 追加ボタンを押した際に気分リストの件数だけが色を残しているので修正する。
- [x] SNS投稿ボタンを押した際に、追加ボタンと気分リストの件数だけが色を残しているので修正する。
