### ISSUE TITLE
movieadd_search.html

### ISSUE THREAD

**Issue by kentaiwami** [kentaiwami/FiNote#6]
### TODO
- [x] autocompleteを調査
- [x] 入力された文字をtmdbのAPIに投げて検索結果を受け取る．
- [x] 検索ボタンを押したらネイティブなアニメーションでキーボードを閉じる．
- [x] 1文字でも入力されたらリセットボタンを表示する.
- [x] リセットボタンを押したら入力したテキストを空にする.
- [x] 検索窓のアニメーションと一緒にキャンセルボタンもアニメーションする.
- [x] キーボードを下げたらリセットボタンも非表示にする．
- [x] キーボードの"検索"を押したらキーボードを閉じる．
- [x] inputイベントが起きたら検索して映画一覧画面と同様にリスト形式で表示する．
- [x] Searchボタンを押した時，フォーカスが外れた時に問い合わせて結果表示を行う．
- [x] 既にローカルに保存されている映画と同じ映画はリスト上に登録済みと表示する．
- [x] スピナーの表示は重複させないようにする。
- [x] 概要が長い(4行を超える)場合は文字列をカットして末尾に…を付与する。
- [x] 追加済みのlist-itemにはチェックマークと追加済みのメッセージを表示する。
- [x] 追加済みのlist-itemをタップしても同様に遷移するように変更する。
- [x] movies画面に戻る際に、再描画する。
- [x] 「見つからない場合」をタップ後に、表示されたリストをタップした後の画面をトップまでスクロールする。

#### Bug
- [x] 映画追加後に戻ってきた際、結果が反映されていない。
- [x] 最初のTMDBの検索結果がある場合から、検索を実行するとスピナーが2個表示される。
- [x] 最初のTMDBの検索結果がない場合からの、さらに検索をタップするとNotFoundErrorが出る。
